# Generated by Django 3.2.16 on 2022-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_merge_0003_auto_20221110_0916_0004_auto_20221110_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('reviewer', 'Reviewer')], default='driver', max_length=8),
        ),
    ]
